<?php
    function sum_menu(){
        $items['sum'] = array(
            'title' => 'Lets Do SUM SUMMATION!',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('sum_form'),
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        $items['sum_success_page'] = array(
            'title' => 'HURRAY! YOU FREAKING DID IT, ALL BY YOURSELF!',
            'page callback' => 'sum_success',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function sum_form(){
        $form['left_number'] = array(
            '#title' => 'Left Number',
            '#type' => 'textfield',
            '#description' => t('Enter your first number'),
            '#element_validate' => array('element_validate_number', 'element_validate_range'),
            '#required' => TRUE,
        );
        $form['right_number'] = array(
            '#title' => 'Right number',
            '#type' => 'textfield',
            '#description' => t('Please enter a number to add to the starting number.'),
            '#element_validate' => array('element_validate_number', 'element_validate_range'),
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'SUM!',
        );

        return $form;
    }

    function element_validate_range($element){
        if ($element['#value'] > 50 || $element['#value'] < -50){
            form_error ($element, t('Please a number between -50 and 50'));
        }
    }

    function sum_form_submit($form, &$form_state){
        $first_number = $form_state['values']['left_number'];
        $second_number = $form_state['values']['right_number'];
        $sum = $first_number + $second_number;
        $_SESSION['sum_output'] = $sum;

        $form_state['redirect'] = 'sum_success_page';
    }

    function sum_success() {
        $answer = $_SESSION['sum_output'];
        return 'You calculated a sum! The answer is: ' . $answer;
    }
