<?php

function ping_pong_menu() {
    $items['ping_pong'] = array(
        'title' => 'Ping Pong Problem',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ping_pong_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    // $items['fake_1'] = array(
    //     'title' => 'this is a fake title look at me',
    //     'page callback' => 'own_function',
    //     'access callback' => TRUE,
    //     'type' => MENU_NORMAL_ITEM,
    // );
    $items['ping_pong_success_page'] = array(
        'title' => 'Success',
        'page callback' => 'ping_pong_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function ping_pong_form() {
    $form['count_goal'] = array(
        '#title' => 'Count Goal',
        '#type' => 'textfield',
        '#description' => t('Please enter the number you want to count up to.'),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

function own_function() {
    return "all the things";
}

function ping_pong_form_submit($form, &$form_state) {
    $count_max = $form_state['values']['count_goal'];
    $i = 1;

    do {
        switch(0) {
            case ($i % 15):
                $pingpong_output[] =  "ping-pong";
                break;
            case ($i % 3):
                $pingpong_output[] =  "ping";
                break;
            case ($i % 5):
                $pingpong_output[] =  "pong";
                break;
            default:
                $pingpong_output[] = $i;
            }
            $i++;
        } while ($i <= $count_max);

    $_SESSION['ping_pong_output'] = $pingpong_output;
    $form_state['redirect'] = 'ping_pong_success_page';
}

function ping_pong_success() {
    $output = '<ul>';
    foreach ($_SESSION['ping_pong_output'] as $value) {
        $output = $output . '<li>' . $value . '</li>';
    }

    $output = $output . '</ul>';
    return "Hooray! $output";
}
