<?php

function word_count_menu() {
  $items['word_count'] = array(
    'title' => 'Word Count',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('word_count_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['word_count_success_page'] = array(
    'title' => 'Success',
    'page callback' => 'word_count_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function word_count_form(){
  $form['text_input'] = array(
    '#title' => 'Text Input',
    '#type' => 'textfield',
    '#description' => t('Please enter the text you would like to count the words of.'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Count!',
  );
  return $form;
}

function word_count_form_submit($form, &$formstate) {
  $input = $form_state['values']['text_input'];
  $words = str_split($input);
  $number_of_words = sizeof($words);

  $_SESSION['word_count_output'] = $number_of_words;
  $form_state['redirect'] = 'word_count_success_page';
}

function word_count_success(){
  $output = $_SESSION['word_count_output'];
  return "Number of words: $output";
}
